# Generated by Django 3.1.1 on 2020-10-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20201004_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_timestamp']},
        ),
    ]
